// General Types
export const SELECT_PERIOD = 'SELECT_PERIOD';
export const UNSUBSCRIBE_PLAN = 'UNSUBSCRIBE_PLAN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_ALL_CAMPAIGN = 'GET_ALL_CAMPAIGN';
export const CAMPAIGN_ERROR = 'CAMPAIGN_ERROR';